New MAUI Examples Added
appt-org/appt-website pull request #60
Opened 2024-08-19 22:25 UTC by arctouch-alejandrovarela

MAUI examples for next features:

- Accessibility action
- Accessibility live region
- Accessibility modal
- Element focus
- Input content type
- Input errors
- Input keyboard type
- Input label
- Keyboard order
- Keyboard shortcuts
- Media audio description
- Media captions live
- Media transcript
- Screen dark mode
- Screen orientation
- Text bold
- Text localization
- Element identification
- Element position
- Input cancellation
- Input gestures
- Input instructions
- Input motion
- Input predictable
- Linting
- Media audio control
- Screen animations
- Screen contrast
- Screen flashes
- Screen headers
- Screen labels
- Screen reflow
- Screen search
- Screen skip
- Screen timing
- Screen title
- Text element
- Text spacing
- Text truncation

2024-08-30 11:37 UTC, ykozlovFivePro requested changes
Good overall! Nice having MAUI code samples for Appt!

Added few more comments to improve overall consistency between code samples and
suggestions to format the long lines of code to avoid having the horizontal scroll.

2024-08-30 11:37 UTC, ykozlovFivePro commented on src/data/code-samples/en/text-bold/net-maui.md
> +While MAUI doesn't offer a way to detect if the user has enabled bold fonts, you can create a method and consume the Native API to detect user preferences.
Maybe rewrite for consistency:
`In MAUI, there is no way to detect if the user has enabled bold font, but you can create a method and consume the Native API to detect user preferences.`

2024-08-30 11:37 UTC, ykozlovFivePro commented on src/data/code-samples/en/text-localization/net-maui.md
> +MAUI offers several ways to handle localization. You can achieve this using the native approach via app resources, but it is recommended to use the .NET approach via [`RESX` files](https://learn.micr
Let's replace the first sentence with:
`In MAUI, there are several ways to handle localization.`

2024-08-30 11:37 UTC, ykozlovFivePro commented on src/data/code-samples/en/text-spacing/net-maui.md
> +MAUI offers a few properties to adjust text spacing:
Let's replace the first sentence with:
In MAUI, there are several properties to adjust text spacing.

2024-08-31 13:44 UTC, JJdeGroot approved these changes

2024-08-31 13:44 UTC, merged